config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  root :to => "pages#show"
  mount Sidekiq::Web => '/sidekiq'
  #OAuth
  get '/auth/google_oauth2', as: :google_login
  get '/auth/google_oauth2/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :logout

  resources :users, only: [:show] do
    resources :lists, only: [:index, :show]
  end
  #API
  namespace :api do
    namespace :v1 do
      resources :lists, only: [:create]
      resources :articles, only: [:create] do
        post '/like', to: 'articles#like'
        post '/dislike', to: 'articles#dislike'
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :url, presence: true
  validates :url, uniqueness: true

  has_many :list_articles, dependent: :destroy
  has_many :lists, through: :list_articles

  acts_as_votable

  def self.create_with_aylien(list, url)
    article = list.articles.create(url: url)
    attributes = AylienService.extract(url)
    article.update(title: attributes[:title])
    article.update(author: attributes[:author])
    article.update(body: TextToSpeech.clean_body(attributes[:article]))
    article.save
    article
  end

  def convert_to_speech
    TextToSpeech.convert(body)
  end

  def export_speech
    AwsService.export_to_s3(convert_to_speech, id.to_s)
  end
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true

  has_many :list_articles, dependent: :destroy
  has_many :articles, through: :list_articles
  belongs_to :user
end

app/models/list_article.rb
class ListArticle < ApplicationRecord
  belongs_to :list
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :email,
            :first_name,
            :last_name, presence: true
  validates :email, uniqueness: true

  has_many :lists, dependent: :destroy
  has_many :articles, through: :lists

  acts_as_voter

  def self.find_or_create_by_oauth(oauth_data)
    user = User.find_by(email: oauth_data[:email])
    return user if user
    user = User.new
    user.email = oauth_data[:email]
    user.first_name = oauth_data[:first_name]
    user.last_name = oauth_data[:last_name]
    user.save
    user
  end
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < Api::V1::BaseController
  def create
    list = current_user.lists.find(params[:list_id])
    @article = Article.find_by(url: params[:url])
    if @article
      list.articles << @article
      render json: @article, :status => 201
    else
      @article = Article.create_with_aylien(list, params[:url])
      ExportJob.perform_later(@article)
      render json: @article, :status => 201
    end
  end

  def like
    article = Article.find(params[:article_id])
    article.liked_by current_user
    render :nothing => true, :status => 201
  end

  def dislike
    article = Article.find(params[:article_id])
    article.disliked_by current_user
    render :nothing => true, :status => 201
  end
end

app/controllers/api/v1/base_controller.rb
class Api::V1::BaseController < ActionController::Base
  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/api/v1/lists_controller.rb
class Api::V1::ListsController < Api::V1::BaseController
  def create
    @list = current_user.lists.create(name: params[:list_name])
    render json: @list, :status => 201
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/concerns/api_controller.rb
class ApiController < ActionController::Base
  helper_method :current_user
  add_flash_types :success, :info, :warning, :danger

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    if current_user && params[:user_id].to_i == current_user.id
      render :index
    else
      render file: "/public/404"
    end
  end

  def show
    if current_user && params[:user_id].to_i == current_user.id
      @list = current_user.lists.find(params[:id])
    else
      render file: "/public/404"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by_oauth(oauth_data)
    session[:user_id] = @user.id
    redirect_to user_lists_path(@user)
  end

  def destroy
    reset_session
    flash[:success] = "Successfully logged out!"
    redirect_to root_path
  end

  private

  def oauth_data
    request.env["omniauth.auth"][:info].slice(:first_name, :last_name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    if current_user && params[:id].to_i == current_user.id
      render :show
    else
      render file: "/public/404"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/text_to_speech.rb
class TextToSpeech
  def self.clean_body(text)
    text = text.gsub("\n",'') if text.gsub("\n",'')
    text
  end
  def self.convert(text)
    streams = text.scan(/.{1,1500}/).map do |piece|
      AwsService.text_to_speech(piece)
    end
    combine_mp3s(streams)
  end

  def self.combine_mp3s(mp3s)
    mp3s.inject("") do |sum, mp3|
      sum += mp3.string
      sum
    end
  end
end

app/views/layouts/_flash.html.erb
<article>
  <% flash.each do |key, value| %>
    <%= content_tag :div, sanitize(value), class: "alert alert-#{key}" %>
  <% end %>
</article>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav navbar-left">
      <% if current_user %>
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "My Lists", user_lists_path(current_user) %></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li>Logged in as <%= current_user.first_name %></li>
        <li><%= link_to "Logout", logout_path, method: "DELETE" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeepUp</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render partial: "/layouts/navbar" %>
    <%= render partial: "/layouts/flash" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<h1>All Lists</h1>
<table class="lists-table">
  <tr>
    <th>List Name</th>
    <th># of Articles</th>
  </tr>
  <% current_user.lists.each do |list| %>
    <tr>
      <td><%= link_to list.name, user_list_path(current_user, list) %></td>
      <td><%= list.articles.count %></td>
    </tr>
  <% end %>
</table>
<form class=list-form>
  <input type="text" name="list" placeholder="Add new list..." required />
  <button type="sub">Add List</button>
</form>

app/views/lists/show.html.erb
<h1><%= @list.name %></h1>
<table class="list-table">
  <tr>
    <th>Article Name</th>
    <th>Points</th>
    <th>Audio</th>
  </tr>
  <% @list.articles.each do |article| %>
  <tr>
    <td><%= article.title %></td>
    <td><%= article.cached_votes_score %>
      <button class="like-button" id="<%= article.id %>">
        Like
      </button>
      <button class="dislike-button" id="<%= article.id %>">
        Dislike
      </button>
    </td>
    <td>
      <audio controls>
        <source src="https://s3.amazonaws.com/keep-up/<%=article.id %>" type="audio/mpeg">
      </audio>
    </td>
  </tr>
  <% end %>
</table>
<form class="article-form" id="<%= @list.id%>">
  <input type="text" name="article" placeholder="Add new article..." required />
  <button type="sub">Add Article</button>
</form>

app/views/pages/show.html.erb
<div class="home-page">
  <h1>Welcome to Keep Up!</h1>
  <button><%= link_to "Login with Google", google_login_path %></button>
</div>

app/views/users/show.html.erb
<h1>Profile</h1>
<p>First Name: <%= current_user.first_name %></p>
<p>Last Name: <%= current_user.last_name %></p>
<p>Email: <%= current_user.email %></p>